name: "multi Event Pipeline" #Name of the pipeline

on:
    push: #Event that trrigger the pipeline
        branches:
            - master

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "Running on master push"
